dist: trusty
sudo: false

language: node_js
node_js:
  - "11.0"

cache:
  directories:
    - ./node_modules
before_script:
  - npm install -g @angular/cli
script:
  - npm install

stages:
  - deploy

jobs:
  include:
    - stage: deploy
      if: branch = develop
      name: "Deploy to develop HEROKU"
      skip_cleanup: true
      env:
        - ENV_DEPLOY=develop
      deploy:
        provider: heroku
        api_key: $HEROKU_API_KEY
        app: m1-server
        on:
          branch: develop
